#!/bin/sh
PATH=scripts:$PATH
# BROWSER="firefox -remote \"openURL(%s,new-tab)\""
echo "# \$BROWSER == '$BROWSER'"
echo "# Using `which clipbrowse`"
perl -Ilib -MClipboard -e 'print qq[#  and $INC{"Clipboard.pm"}\n]'
check() {
    echo -n Checking "$1"
    perl -MClipboard -e 'Clipboard->copy($ARGV[0])' "$1" || exit 1
    clipbrowse || exit 1
    echo ' ok'
}
check 'http://cpan.org'
check cpan
check "'"
check '"'
check '()*&#(*&$;$$!!!#$@#'
