#!/usr/bin/perl -w
use strict;
use lib 'lib';
use Clipboard;
use IO::All;
my $save = Clipboard->paste;
print "Found: ", Clipboard->paste, "\n";
Clipboard->copy('robot');
print "Found: ", Clipboard->paste, "\n";
Clipboard->copy($save);
