#!/usr/bin/perl -w
use strict;
use lib 'lib';
use Clipboard;
use IO::All;
my $save = Clipboard->paste;
print "Original: ", Clipboard->paste, "\n";
Clipboard->copy('looks like Clipboard->copy works');
print "     Now: ", Clipboard->paste, "\n";
Clipboard->copy($save);
print "(Restored original clipboard)\n"
